Footer component
lexomut/Pointing-Poker pull request #1
Opened 2021-09-06 18:34 UTC by OKitel

Screenshot: 
![image](https://user-images.githubusercontent.com/79774026/132252912-43eec54e-0232-40ff-acd8-69e2681b50ff.png)

2021-09-07 09:46 UTC, lexomut approved these changes

2021-09-08 19:10 UTC, MarharytaKrasikava requested changes

2021-09-08 19:10 UTC, MarharytaKrasikava commented on src/App.tsx
> +        <div style={{ position: 'relative', minHeight: '100vh' }}>
почему инлайновые стили? используйте классы, id

2021-09-08 19:10 UTC, MarharytaKrasikava commented on src/components/footer/Footer.tsx
> +                    rel="noreferrer"
здесь вместо повторяющихся блоков лучше создать отдельный мини-компонент и массив данных со ссылками на гитхабы и имена создателей, а затем проитерировать по этому массиву

2021-09-08 19:10 UTC, MarharytaKrasikava commented on src/components/footer/Footer.tsx
> +export default Footer;
избегайте дефолтных экспортов. Вместо этого пишется export const Footer = ...

2021-09-08 19:10 UTC, MarharytaKrasikava commented on src/components/footer/index.ts
> +export { default as Footer } from './Footer';
тут надо поправить после избавления от дефолтного экспорта

2021-09-08 19:12 UTC, OKitel commented on src/components/footer/Footer.tsx
> +export default Footer;
eslint требует дефолтного экспорта, игнорировать?

2021-09-08 19:14 UTC, OKitel commented on src/App.tsx
> +        <div style={{ position: 'relative', minHeight: '100vh' }}>
Здесь писала инлайновый стиль, чтобы пример в апе адекватно выглядел. Ведь этот компонент будет использован на других страницах. Поэтому и не создавала класс для апп

2021-09-08 19:16 UTC, OKitel commented on src/components/footer/Footer.tsx
> +                    rel="noreferrer"
Ок, сейчас сделаю

2021-09-08 19:29 UTC, MarharytaKrasikava commented on src/App.tsx
> +        <div style={{ position: 'relative', minHeight: '100vh' }}>
инлайновые стили тяжело переопределить, надо их избегать. Поэтому лучше отдельный файл со стилями создать

2021-09-08 19:34 UTC, OKitel commented on src/components/footer/Footer.tsx
> +                    rel="noreferrer"
Готово

2021-09-08 19:37 UTC, MarharytaKrasikava commented on src/components/footer/Footer.tsx
> +export default Footer;
да, похоже придется отключить в .eslintrc rules
"rules": {
     "import/prefer-default-export": "off",
     ...
}

2021-09-08 19:45 UTC, OKitel commented on src/components/footer/index.ts
> +export { default as Footer } from './Footer';
Сделано

2021-09-08 19:56 UTC, MarharytaKrasikava requested changes

2021-09-08 19:56 UTC, MarharytaKrasikava commented on src/components/footer/Footer.tsx
> +function GithubLink(props: { author: Author }) {
это надо в отдельный файл, пожалуйста.

2021-09-08 19:56 UTC, MarharytaKrasikava commented on src/components/footer/Footer.tsx
> +const authors: Author[] = [
а это тоже надо в отдельный файл, только в самом корне создать папку data и туда всякого рода данные помещать

2021-09-08 20:00 UTC, MarharytaKrasikava requested changes

2021-09-08 20:00 UTC, MarharytaKrasikava commented on src/index.tsx
> +import './style.module.scss';
тут надо упорядочить - стили импортить после компонентов и модулей, в самом конце

2021-09-08 20:10 UTC, OKitel commented on src/components/footer/Footer.tsx
> +function GithubLink(props: { author: Author }) {
Сделано

2021-09-08 20:10 UTC, OKitel commented on src/components/footer/Footer.tsx
> +const authors: Author[] = [
done

2021-09-08 20:15 UTC, MarharytaKrasikava approved these changes

2021-09-08 21:11 UTC, merged