Game card
lexomut/Pointing-Poker pull request #10
Opened 2021-09-10 23:02 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/132931842-265c2cce-2223-43d6-8e17-d95635a6b186.png)

2021-09-12 16:03 UTC, MarharytaKrasikava requested changes

2021-09-12 16:03 UTC, MarharytaKrasikava commented on src/components/GameCards/CardBack.tsx
> +};
пустая строка перед компонентом

2021-09-12 16:03 UTC, MarharytaKrasikava commented on src/components/GameCards/CardMenu.tsx
> +const ITEM_HEIGHT = 48;
константы лучше вынести в отдельный файл constants.ts внутри директории компонента или в shared в зависимости от масштабов применения

2021-09-12 16:03 UTC, MarharytaKrasikava commented on src/components/GameCards/CoffeeCard.tsx
> +export const CoffeeCard: React.FC = () => {
похоже, что выносить этот компонент не нужно

2021-09-12 16:03 UTC, MarharytaKrasikava commented on src/App.tsx
> +            </div>
Почему этот `<div>` не вынести в отдельный блочный компонент?

2021-09-13 23:06 UTC, OKitel commented on src/components/GameCards/CardBack.tsx
> +};
done

2021-09-13 23:06 UTC, OKitel commented on src/components/GameCards/CardMenu.tsx
> +const ITEM_HEIGHT = 48;
done

2021-09-13 23:07 UTC, OKitel commented on src/components/GameCards/CoffeeCard.tsx
> +export const CoffeeCard: React.FC = () => {
Я переписала, чтобы не выносить этот компонент, но по-моему получилось хуже, чем было.

2021-09-13 23:07 UTC, OKitel commented on src/App.tsx
> +            </div>
done

2021-09-14 15:12 UTC, MarharytaKrasikava requested changes

2021-09-14 15:12 UTC, MarharytaKrasikava commented on src/components/GameCards/DemoGameCards.tsx
> +            <GameCard value={1} isEditable scoreType="SP" />
В будущем это будет массив, который нужно будет запрашивать с сервера и отображать через итерирование. Так что может завести пока фейковый массив данных

2021-09-14 15:12 UTC, MarharytaKrasikava commented on src/components/GameCards/DemoGameCards.tsx
> +            <GameCard gameCard={false} />
а эта кофе-карта будет отдельно от [].map(). Ее можно просто захардкодить тут
 `<Paper elevation={3} className={styles.card}>
            <FreeBreakfastOutlinedIcon className={styles.coffee} />
 </Paper>`

2021-09-14 15:12 UTC, MarharytaKrasikava commented on src/components/GameCards/DemoGameCards.tsx
> +            <CardBack back="bgMountains" />
и тут отдельный мэп по массиву данных будет

2021-09-14 19:04 UTC, OKitel commented on src/components/GameCards/CoffeeCard.tsx
> +export const CoffeeCard: React.FC = () => {
захардкодила coffee card

2021-09-14 19:04 UTC, OKitel commented on src/components/GameCards/DemoGameCards.tsx
> +            <GameCard value={1} isEditable scoreType="SP" />
есть массив

2021-09-14 19:04 UTC, OKitel commented on src/components/GameCards/DemoGameCards.tsx
> +            <GameCard gameCard={false} />
done

2021-09-14 19:04 UTC, OKitel commented on src/components/GameCards/DemoGameCards.tsx
> +            <CardBack back="bgMountains" />
done

2021-09-15 12:32 UTC, MarharytaKrasikava requested changes

2021-09-15 12:32 UTC, MarharytaKrasikava commented on src/components/GameCards/CardMenu.tsx
> +        <div>
а несет ли этот див тут какую-то стилистическую нагрузку? или можно фрагментом обернуть?

2021-09-15 13:42 UTC, OKitel commented on src/components/GameCards/CardMenu.tsx
> +        <div>
исправила

2021-09-15 17:29 UTC, MarharytaKrasikava approved these changes

2021-09-15 21:46 UTC, merged