Router
lexomut/Pointing-Poker pull request #11
Opened 2021-09-11 00:10 UTC by OKitel

Add simple router

2021-09-11 08:35 UTC, lexomut requested changes
еще можно сделать маршрут http://host/123456789 , когда по нему переходишь то,как будто уже нажал на кнопку присоединится к игре и ввел id игры. 
а стартовая страница проверяет через useparam  и если такая игра есть, то открывает форму регистрации.

2021-09-11 13:01 UTC, OKitel commented
@lexomut сделал еще роут к попапу для подключения к существующей игре. Правильно?

2021-09-13 15:45 UTC, lexomut reviewed
мне кажется нужно так сделать:
```
<Route exact path="/:id">
                    Popup connect to lobby
                </Route>
```
а на стартовой странице проверять есть id или нет и открывать попап

2021-09-15 13:33 UTC, MarharytaKrasikava requested changes

2021-09-15 13:33 UTC, MarharytaKrasikava commented on src/components/invitation/Invitation.tsx
> +        <Switch>
Надо организовать вместо такой схемы редирект  https://reactrouter.com/web/api/Redirect

2021-09-15 15:20 UTC, OKitel commented on src/components/invitation/Invitation.tsx
> +        <Switch>
Переделала

2021-09-15 17:24 UTC, MarharytaKrasikava approved these changes

2021-09-16 13:44 UTC, lexomut approved these changes

2021-09-16 13:52 UTC, merged