Websoket func and usecontext reduser
lexomut/Pointing-Poker pull request #13
Opened 2021-09-13 15:47 UTC by lexomut

посмотрите заготовку по функции с вебсокетами и useContext и reduser

2021-09-14 13:30 UTC, MarharytaKrasikava requested changes

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/App.tsx
>  import styles from './style.module.scss';
импорт стилей самым последним должен идти

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/ConnectWS.ts
> +            // console.log('подключение c сервером установлено');
убрать комментарий

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/HandlerMessageWS.ts
> +                `пользователь ${message.userName} написал сообшение: ${message.chatMessage}`,
сообЩение. И наверно все сообщения с заглавной буквы начинаться должны

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/state/reduser.ts
> +import { ChatMessage, State } from '../types/State';
в названии файла ошибка - reduCer

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/temp.tsx
> +            {/* eslint-disable-next-line react/button-has-type */}
а почему кнопке не назначить type="button"? Вообще не должно в проекте быть таких строк

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/HandlerMessageWS.ts
> +            console.log(`пользователь ${message.userName} подключился`);
в проекте не должно быть консоль логов

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/HandlerMessageWS.ts
> +            console.log(
и тут то же самое насчет логов

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/HandlerMessageWS.ts
> +export function HandlerMessageWS(message: WSMessageBody, dispatch: (arg: Action) => unknown): void {
Правилильнее по-английски это имя будет звучать WSMessageHandler (последним идет основное слово)

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/temp.tsx
> +    useEffect(() => {}, []);
а зачем тут пустой useEffect?

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/state/reduser.ts
> +    | { type: 'doSameThink'; payLoad: unknown };
какой-то странный тип...

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/state/reduser.ts
> +        case 'addChatMessage': {
все строковые имена экшнов надо выносить в файл ActionNames.ts (например, `const ADD_CHAT_MESSAGE = 'addChatMessage'`). B и оттуда их импортить

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/ConnectWS.ts
> +const dummy: WSMessageBody = {
названия переменных должны максимально отражать суть. Dummy это прилагательное - не хватает существительного https://afedyanin.wordpress.com/2015/01/23/clean-code-naming/

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/ConnectWS.ts
> +class Connect {
Connect больше похож на название метода, потому что это глагол. Класс это какая-то сущность, поэтому должен содержать как минимум одно существительное

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/ConnectWS.ts
> +        this.socket = new WebSocket(url);
может, создавать вебсокет при создании класса было бы логичнее?

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/api/ConnectWS.ts
> +        return this.socket;
а зачем тут возвращать что-то?

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/temp.tsx
> +            <button onClick={() => submitHandler()}> send</button>
Текст кнопки пишется с заглавной баквы без пробела перед ним

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/temp.tsx
> +                        <span>{chatMessage.author} </span> <span> {chatMessage.text}</span>
пробелы уберите, пожалуйста, ненужные

2021-09-14 13:30 UTC, MarharytaKrasikava commented on src/temp.tsx
> +            chatMessage: firstName,
а ввод текста сообщения это планы на будущее?

2021-09-16 14:57 UTC, lexomut commented on src/App.tsx
>  import styles from './style.module.scss';
done

2021-09-16 15:06 UTC, lexomut commented on src/api/HandlerMessageWS.ts
> +                `пользователь ${message.userName} написал сообшение: ${message.chatMessage}`,
done

2021-09-16 15:07 UTC, lexomut commented on src/state/reduser.ts
> +import { ChatMessage, State } from '../types/State';
done

2021-09-16 15:09 UTC, lexomut commented on src/temp.tsx
> +            {/* eslint-disable-next-line react/button-has-type */}
а я понять не мог, почему линтер ругается 
done

2021-09-16 15:09 UTC, lexomut commented on src/api/ConnectWS.ts
> +        this.socket = new WebSocket(url);
done

2021-09-16 15:10 UTC, lexomut commented on src/api/ConnectWS.ts
> +        return this.socket;
убрал

2021-09-16 15:10 UTC, lexomut commented on src/temp.tsx
> +            <button onClick={() => submitHandler()}> send</button>
done

2021-09-16 15:11 UTC, lexomut commented on src/temp.tsx
> +                        <span>{chatMessage.author} </span> <span> {chatMessage.text}</span>
done

2021-09-16 15:11 UTC, lexomut commented on src/temp.tsx
> +            chatMessage: firstName,
да

2021-09-16 15:32 UTC, lexomut commented on src/state/reduser.ts
> +    | { type: 'doSameThink'; payLoad: unknown };
я не знаю как лучше за типизировать объекты   Action

2021-09-16 15:33 UTC, lexomut commented on src/api/HandlerMessageWS.ts
> +            console.log(
а можно позже убрать?

2021-09-16 15:33 UTC, lexomut commented on src/api/HandlerMessageWS.ts
> +            console.log(`пользователь ${message.userName} подключился`);
а можно позже убрать?

2021-09-16 19:44 UTC, MarharytaKrasikava requested changes

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/temp.tsx
> +        <div>
обязателен ли тут этот div? или заменяется на <>?

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/temp.tsx
> +            <div>
и тут тоже

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/temp.tsx
> +                    // eslint-disable-next-line react/no-array-index-key
Уберите эту строку. У меня не ругается без нее - специально проверила. И вообще, используйте эти дизейблы правил только как временную меру, пожалуйста (как с консоль логами)

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +    async connection(): Promise<void> {
то же самое

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +    globalDispatcher: (arg: Action) => unknown;
имя метода должно быть глаголом

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +        this.globalState = globalState;
тут надо глобал стейт убрать, а как агрументы передавать только два его поля - currentUser и game

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +            userName: this.globalState.currentUser.firstName,
this.currentUser

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +            userName: this.globalState.currentUser.firstName,
тут у вас есть отдельно заведенное свойство класса - this.currentUser

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +// eslint-disable-next-line import/no-cycle
это уже можно удалить

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +// eslint-disable-next-line import/no-cycle
нельзя правила дизейблить. Создайте отдельный интерфейс WS в тайпах

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/state/reducer.ts
> +// eslint-disable-next-line import/no-cycle
и это удалить, когда создадите интерфейс

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +    private socket: WebSocket | undefined;
все свойства класса должны определяться перед методами

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +        this.connection();
в конструкторе нельзя вызывать методы. Вместо этого после создания экземпляра класса вызывается его метод.

2021-09-16 19:44 UTC, MarharytaKrasikava commented on src/api/WSHandlerMessage.ts
> +export function WSHandlerMessage(message: WSMessageBody, dispatch: (arg: Action) => unknown): void {
WSMessageHandler. И название файла тоже, пожалуйста

2021-09-17 13:11 UTC, lexomut commented on src/api/WSHandlerMessage.ts
> +export function WSHandlerMessage(message: WSMessageBody, dispatch: (arg: Action) => unknown): void {
done

2021-09-17 13:18 UTC, lexomut commented on src/api/WSProvider.ts
> +        this.connection();
done

2021-09-17 13:18 UTC, lexomut commented on src/api/WSProvider.ts
> +    private socket: WebSocket | undefined;
done

2021-09-17 16:16 UTC, lexomut commented on src/api/WSProvider.ts
> +    globalDispatcher: (arg: Action) => unknown;
done

2021-09-17 16:16 UTC, lexomut commented on src/api/WSProvider.ts
> +// eslint-disable-next-line import/no-cycle
done

2021-09-17 16:16 UTC, lexomut commented on src/state/reducer.ts
> +// eslint-disable-next-line import/no-cycle
done

2021-09-17 16:18 UTC, lexomut commented on src/temp.tsx
> +                    // eslint-disable-next-line react/no-array-index-key
done

2021-09-17 16:18 UTC, lexomut commented on src/temp.tsx
> +            <div>
done

2021-09-17 17:04 UTC, lexomut commented on src/api/WSProvider.ts
> +            userName: this.globalState.currentUser.firstName,
done

2021-09-17 17:04 UTC, lexomut commented on src/api/WSProvider.ts
> +            userName: this.globalState.currentUser.firstName,
done

2021-09-17 17:04 UTC, lexomut commented on src/api/WSProvider.ts
> +// eslint-disable-next-line import/no-cycle
done

2021-09-17 17:09 UTC, lexomut commented on src/api/WSProvider.ts
> +        this.globalState = globalState;
сделал так:
`    constructor({ currentUser, game }: GlobalState, globalDispatch: Dispatch<Action>) {`
     `   this.globalDispatch = globalDispatch;`
   `    this.currentUser = currentUser;`
  `      this.game = game;`
 `   }`


Dispatch обязательно нужен

2021-09-17 17:14 UTC, lexomut commented on src/api/WSProvider.ts
> +    async connection(): Promise<void> {
done

2021-09-17 17:15 UTC, lexomut commented on src/temp.tsx
> +        <div>
done

2021-09-17 21:16 UTC, MarharytaKrasikava approved these changes

2021-09-17 21:16 UTC, MarharytaKrasikava commented on src/App.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
эх, правила дизейблить нельзя....

2021-09-18 11:16 UTC, lexomut commented on src/App.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
извиняюсь

2021-09-18 11:22 UTC, OKitel approved these changes

2021-09-18 11:33 UTC, merged