chat icon in header
lexomut/Pointing-Poker pull request #15
Opened 2021-09-15 13:20 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/133440823-194f8a62-69af-4918-88ac-b6cfbd1c488a.png)

2021-09-16 19:50 UTC, MarharytaKrasikava requested changes

2021-09-16 19:50 UTC, MarharytaKrasikava commented on src/components/header/Header.tsx
> +                        <SpeakerNotesIcon />
лучше наверно тернарник эля тих иконок сделать (40я и 49я строки). И тогда будет один онклик хендлер, где аргументом передать isChatOpen

2021-09-16 19:58 UTC, OKitel commented on src/components/header/Header.tsx
> +                        <SpeakerNotesIcon />
Переделала

2021-09-17 08:18 UTC, MarharytaKrasikava approved these changes

2021-09-17 17:27 UTC, lexomut approved these changes

2021-09-17 19:34 UTC, merged