edit classNames and css
lexomut/Pointing-Poker pull request #19
Opened 2021-09-18 13:50 UTC by lexomut

2021-09-19 13:18 UTC, MarharytaKrasikava requested changes

2021-09-19 13:18 UTC, MarharytaKrasikava commented on src/api/ReadAvatar.ts
> -
правильно оставлять пустую строку вконце

2021-09-19 13:18 UTC, MarharytaKrasikava commented on src/api/url.js
> -
и тут

2021-09-19 13:18 UTC, MarharytaKrasikava commented on src/api/CreateUser.ts
>  export interface CreateUser {
имя интерфейса должно быть существительным.

2021-09-19 13:18 UTC, MarharytaKrasikava commented on src/api/CreateUser.ts
>  export interface CreateUser {
А почему надо в функцию именно объект передавать, а не набор аргументов?

2021-09-19 19:41 UTC, lexomut commented on src/api/CreateUser.ts
>  export interface CreateUser {
без разницы, а как лучше? я не знаю

2021-09-21 20:43 UTC, MarharytaKrasikava commented on src/api/CreateUser.ts
>  export interface CreateUser {
лучше аргументы

2021-09-21 20:46 UTC, MarharytaKrasikava requested changes

2021-09-21 20:46 UTC, MarharytaKrasikava commented on src/api/CreateUser.ts
>  export interface CreateUser {
и не нужен тогда лишний интерфейс

2021-09-24 20:51 UTC, MarharytaKrasikava requested changes

2021-09-24 20:51 UTC, MarharytaKrasikava commented on src/App.tsx
> +                        {' '}
с какой целью пробел?

2021-09-29 09:45 UTC, closed without merging