Chat component
lexomut/Pointing-Poker pull request #20
Opened 2021-09-19 19:43 UTC by lexomut

![Screenshot_1](https://user-images.githubusercontent.com/61846514/133940856-42878671-8106-482b-be21-33228deb4947.png)

2021-09-22 21:13 UTC, OKitel requested changes

2021-09-22 21:13 UTC, OKitel commented on src/api/WSMessageHandler.ts
> +            console.log(`Пользователь ${message.user.firstName} подключился`);
Консоль логи нужно убрать.

2021-09-22 21:13 UTC, OKitel commented on src/api/WSMessageHandler.ts
> +                `Пользователь ${message.user.firstName} написал сообщение: ${message.chatMessage?.text}`,
Консоль лог не нужен

2021-09-22 21:13 UTC, OKitel commented on src/api/WSMessageHandler.ts
>                      id: new Date().getTime().toString(36) + Math.random().toString(36).slice(2),
Очень мудрено, но отлично работает)

2021-09-22 21:13 UTC, OKitel commented on src/components/chat/ChatMessageComponent.tsx
> +import './chat.scss';
Не ошибка, но мы договаривались использовать модули для стилей, чтобы не пересекались классы из разных компонентов. Для этого нужно писать chat.module.scss, а потом при импорте писать `import styles from './chat.module.scss'`. А в месте использования `<div className={styles.chat__message}> </div>`.

2021-09-22 21:13 UTC, OKitel commented on src/components/chat/input.tsx
> +                    Send
Хотелось бы, чтобы сообщения могли отправляться не только при нажатии на кнопку, но и при нажатии Enter. Как вариант можно обернуть в форму: [смотри пример.](https://stackoverflow.com/questions/58699898/submit-a-form-using-enter-key-with-material-ui-core-button-in-react-js )

2021-09-22 21:13 UTC, OKitel commented on src/types/user.ts
> +    jobPosition: string;
`jobPosition?: string;` опциональный пункт

2021-09-22 21:13 UTC, OKitel commented on src/components/chat/ChatText.tsx
> +import clsx from 'clsx';
```suggestion
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import clsx from 'clsx';
```

2021-09-22 21:13 UTC, OKitel commented on src/components/chat/ChatText.tsx
> +
```suggestion
```

2021-09-22 21:13 UTC, OKitel commented on src/components/chat/chat.scss
> +
```suggestion
```

2021-09-22 21:13 UTC, OKitel commented on src/types/GlobalState.ts
> +    anything?: string;
Что здесь должно храниться?

2021-09-23 10:50 UTC, lexomut commented on src/types/GlobalState.ts
> +    anything?: string;
не знаю, сделал на будушее

2021-09-23 12:04 UTC, lexomut commented on src/components/chat/input.tsx
> +                    Send
сделал как в примере но , все равно не по ентеру не входит, наверное потому что элеметы формы это компоненты MUI

2021-09-23 15:04 UTC, OKitel approved these changes
Много мест с закомментированными консоль логами, не вижу в них смысла.

2021-09-23 15:04 UTC, OKitel commented on src/api/WSMessageHandler.ts
> +                    user: message.user,
Не вижу смысла в закомментированном коде

2021-09-23 15:04 UTC, OKitel commented on src/api/WSMessageHandler.ts
> +            // );
То же самое

2021-09-23 18:46 UTC, closed without merging