Main page with connections
lexomut/Pointing-Poker pull request #21
Opened 2021-09-20 17:07 UTC by lexomut

стартовая страница, создаётся или проверяется объект игры в базе и записывается в глобальный стейт, также создается объект currenUser в базе и тоже записывается в глобальный стейт, после этого  переходит на страницу лоби.

2021-09-22 23:10 UTC, OKitel commented on src/App.tsx
> +import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
Зачем второй раз роутер??? В index.tsx уже есть.

2021-09-22 23:11 UTC, OKitel commented on src/App.tsx
> +    // }, []);
Это так и должно быть закомментировано? Если в чате и девелопе уже это раскоментировано?

2021-09-22 23:13 UTC, OKitel commented on src/App.tsx
> +                                </Route>
Зачем этот путь, эти компоненты из апа нужно убрать, потому что это демо.

2021-09-22 23:13 UTC, OKitel commented on src/App.tsx
> +                                <Route path="/">
Есть ли необходимость переставлять пути в роутере и почему не указывается exact path?

2021-09-24 22:06 UTC, MarharytaKrasikava requested changes

2021-09-24 22:06 UTC, MarharytaKrasikava commented on .eslintrc.js
> +};
не поняла, что за изменение?

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/Components/ConnectForm/ConnectForm.tsx
> +        if (!url) return;
а это ожидаемо, что если нет урла в форме, то будет бесконечный прогресс?

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/Components/ConnectForm/ConnectForm.tsx
> +            console.log(game);
удалить лог

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/Components/ConnectForm/ConnectForm.tsx
> +    const [isConnecting, setIsConnecting] = useState(false);
нужно использовать один комплексный стейт, когда больше одного-двух useState

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/Components/RegistrationForm/RegistrationForm.tsx
> +    const [avatar, setAvatar] = useState<File>();
вообще надо по-хорошему один составной стейт организовать тут, в компоненты вынести инпуты и колбэки по изменению стейта передать туда. А тот этот компонент очень огромный получился. Но если нет совсем времени, оставляйте

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/Components/RegistrationForm/RegistrationForm.tsx
> +            if (data) {
data может быть неопределенным значением тут вообще?

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/Components/RegistrationForm/RegistrationForm.tsx
> +                if (!currentUser.userID) return;
`if (!currentUser?.userID) return;`

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/Components/UploadButton/UploadButton.tsx
> +// import styles from './UploadButton.module.scss';
коммент ненужный

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/CreateUser.ts
>  export interface CreateUser {
так интерфейсы не называют - глаголами)

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/WSMessageHandler.ts
> +            // );
коммент

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/WSMessageHandler.ts
> +            // );
коммент

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +            // console.log('Open new WebSocket connection');
коммент

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +            // console.log('Ошибка соединения с сервером');
коммент

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +                // console.log('Получено сообщение с типом:', message.event);
комменты

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +                // console.log(event.data, '  ', e);
комменты

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +            // console.log('Ошибка отправки', e);
комменты

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/components/chat/Chat.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
нельзя правила отключать

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/components/chat/input.tsx
> +    const send = useCallback(
зачем useCallback? он используется для тяжеловесных вычислений, которые нишний раз лучше не тригерить

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/components/chat/input.tsx
> +                <Input
надо в отдельный компонент выносить инпут и кнопку с их стейтами и хендлерами (при наличии времени)

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/state/reducer.ts
> +            const arr: Array<ChatMessage> = globalState.game.chatMessages;
нельзя так переменные называть. Messages, по-моему, гораздо понятнее. И раз здесьзаведена переменная, то ниже при возвращении стейта можно ее использовать

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/state/reducer.ts
> +            game.gameID = globalState.game.gameID;
по-моему это действие тут лишнее

2021-09-24 22:06 UTC, MarharytaKrasikava commented on src/state/reducer.ts
> +            return state;
вы копируете по ссылке и возвращаете измененный стейт, а стейт менять нельзя. Поэтому нужно спредом скопированный объект возвращать, как и в предыдущих случаях

2021-09-24 22:06 UTC, MarharytaKrasikava commented on tsconfig.json
> +}
тоже странное изменение

2021-09-25 07:21 UTC, lexomut commented on .eslintrc.js
> +};
мержил с веткой ленара,  видимо у него были другие настройки eslint . у меня последние с девелоп

2021-09-25 07:49 UTC, lexomut commented on src/Components/ConnectForm/ConnectForm.tsx
> +        if (!url) return;
тоже компоненты Ленара, некогда разбирается , сабмитится 2 раза , и второй раз без урл,  второй раз без этого условия приводит к ошибке , с условием работает отлично..

2021-09-25 07:52 UTC, lexomut commented on src/Components/ConnectForm/ConnectForm.tsx
> +            console.log(game);
удалил

2021-09-25 07:56 UTC, lexomut commented on src/Components/ConnectForm/ConnectForm.tsx
> +    const [isConnecting, setIsConnecting] = useState(false);
хорошо, буду использовать вашу рекомендацию в дальнейшем коде ,  тут пока оставлю как есть.

2021-09-25 08:05 UTC, lexomut commented on src/Components/RegistrationForm/RegistrationForm.tsx
> +    const [avatar, setAvatar] = useState<File>();
хорошо, все понял, в следующий раз сделаю как вы написали.

2021-09-25 08:15 UTC, lexomut commented on src/state/reducer.ts
> +            const arr: Array<ChatMessage> = globalState.game.chatMessages;
не понял, вы про chatMessages?  
chatMessages чтоб не путать сообщениями в чат со служебными сообщениями с сервером

2021-09-25 12:15 UTC, lexomut commented on src/state/reducer.ts
> +            return state;
вот по этому поводу я хотел  вас спросить,  я сразу делал как вы написали все редъюсеры работают как надо , но вот этот редъюсер  не работает,  почему-то и  provider не добавляется в globalState.
```
case ADD_WS_PROVIDER_TO_GLOBAL_STATE: {
            const { ws } = globalState;
            const provider = action.payLoad;
            return { ...globalState, ws: { ...ws, provider } };
```
а если сначала мутируешь globalState-  работает отлично
```
case ADD_WS_PROVIDER_TO_GLOBAL_STATE: {
            const provider = action.payLoad;
            const { ws } = globalState;
            ws.provider = provider;
            return { ...globalState, ws };
        }
```

2021-09-25 12:33 UTC, lexomut commented on src/state/reducer.ts
> +            game.gameID = globalState.game.gameID;
я уже не помню но кажется я исправил это на  стороне сервера, почему  приходил объект игры по умолчанию

2021-09-25 12:35 UTC, lexomut commented on tsconfig.json
> +}
это так смержилось

2021-09-25 12:41 UTC, lexomut commented on src/components/chat/input.tsx
> +                <Input
не ужели так сильно нужно дробить этот компонент? инпут и кнопка непереиспользуемые компоненты Mui. компоненнт и так получился не большим.

2021-09-25 12:47 UTC, lexomut commented on src/Components/RegistrationForm/RegistrationForm.tsx
> +            if (data) {
наверное рудимент. убрал

2021-09-25 12:48 UTC, lexomut commented on src/Components/UploadButton/UploadButton.tsx
> +// import styles from './UploadButton.module.scss';
убрал

2021-09-25 12:57 UTC, lexomut commented on src/components/chat/Chat.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
читал, искал не  знаю как это убрать, подскажите пожалуйста
он просит добавить в массив зависимостей  useEffectа - globalState  . а мне нужно чтоб он сработал только один раз.

2021-09-25 13:20 UTC, lexomut commented on src/components/chat/input.tsx
> +    const send = useCallback(
если сделать без него то будет такая ошибка.
ESLint: The 'send' function makes the dependencies of useEffect Hook (at line 40) change on every render. To fix this, wrap the definition of 'send' in its own useCallback() Hook.(react-hooks/exhaustive-deps)

2021-09-25 13:34 UTC, lexomut commented on src/api/WSProvider.ts
> +            // console.log('Ошибка отправки', e);
коммент убрал, вывод шибки в консоль оставил

2021-09-25 13:34 UTC, lexomut commented on src/api/WSProvider.ts
> +                // console.log(event.data, '  ', e);
коммент убрал, вывод шибки в консоль оставил

2021-09-25 13:35 UTC, lexomut commented on src/api/WSProvider.ts
> +                // console.log('Получено сообщение с типом:', message.event);
коммент убрал, вывод шибки в консоль оставил

2021-09-25 13:35 UTC, lexomut commented on src/api/WSProvider.ts
> +            // console.log('Ошибка соединения с сервером');
коммент убрал, вывод шибки в консоль оставил

2021-09-25 13:35 UTC, lexomut commented on src/api/WSProvider.ts
> +            // console.log('Open new WebSocket connection');
убрал

2021-09-25 13:41 UTC, lexomut commented on src/api/WSMessageHandler.ts
> +            // );
убрал

2021-09-25 13:46 UTC, lexomut commented on src/api/CreateUser.ts
>  export interface CreateUser {
исправил на CreateUserInterface

2021-09-25 14:03 UTC, lexomut commented on src/Components/RegistrationForm/RegistrationForm.tsx
> +                if (!currentUser.userID) return;
исправил, спасибо

2021-09-26 10:47 UTC, lexomut commented on src/components/chat/Chat.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
получилось сделать , разбив на 2 useEfect и не не передавая   globalState в конструктор  WSProvider

2021-09-26 10:48 UTC, lexomut commented on src/state/reducer.ts
> +            return state;
исправил

2021-09-26 15:27 UTC, MarharytaKrasikava requested changes

2021-09-26 15:27 UTC, MarharytaKrasikava commented on src/components/chat/input.tsx
> +        document.addEventListener('keydown', listener);
а не проще было бы организвать отправку по 'Enter' в onChange хендлере и там проверять код клавиши?

2021-09-26 15:27 UTC, MarharytaKrasikava commented on src/components/chat/input.tsx
> +                <Input
куча пропсов - это уже показатель. Но можете оставить

2021-09-26 15:27 UTC, MarharytaKrasikava commented on src/pages/MainPage/MainPage.tsx
> +        <div className={styles.main_page}>
лишний див. Стиль можно к main применить, а его убрать

2021-09-26 15:27 UTC, MarharytaKrasikava commented on src/state/reducer.ts
> +            const arr: Array<ChatMessage> = globalState.game.chatMessages;
нет, я про arr

2021-09-26 15:27 UTC, MarharytaKrasikava commented on src/types/GlobalState.ts
> +    | { type: 'setGame'; payLoad: Game }
экшен неймы у вас же в переменные вынесены где-то (ADD_CHAT_MESSAGE и др.)

2021-09-26 15:27 UTC, MarharytaKrasikava commented on src/Components/ConnectForm/ConnectForm.tsx
> +        if (!url) return;
а если поставить это условие перед `setIsConnecting(true)`?

2021-09-26 15:27 UTC, MarharytaKrasikava commented on src/api/WSProvider.ts
> +            console.log(this.game);
еще один лог лишний по-моему

2021-09-26 15:41 UTC, lexomut commented on src/api/WSProvider.ts
> +            console.log(this.game);
да забыл убрать, когда отлаживал.

2021-09-26 15:59 UTC, lexomut commented on src/types/GlobalState.ts
> +    | { type: 'setGame'; payLoad: Game }
исправил

2021-09-26 16:02 UTC, lexomut commented on src/pages/MainPage/MainPage.tsx
> +        <div className={styles.main_page}>
исправил

2021-09-26 16:39 UTC, lexomut commented on src/components/chat/input.tsx
> +        document.addEventListener('keydown', listener);
исправил

2021-09-26 18:16 UTC, MarharytaKrasikava approved these changes

2021-09-27 08:32 UTC, merged