Lobby
lexomut/Pointing-Poker pull request #24
Opened 2021-09-29 09:52 UTC by lexomut

название игры , игроки, вопросы добавляются и синхронизируются  другими игроками,
настройки при изменении попадают в globalState, и отправляются на сервер по нажатию на кнопку старт игры
чат открывается и закрывается по кнопке

2021-09-29 15:51 UTC, OKitel commented on public/index.html
>      <meta charset="utf-8"/>
Эти линки не нужно убирать, это для того, чтобы на любом типе устройств нормально открывался фавикон.

2021-09-29 15:53 UTC, OKitel commented on .vscode/settings.json
> +=======
Это похоже на незарезолвенный конфликт

2021-09-29 16:40 UTC, OKitel commented on .gitignore
Это не нужно убирать. eslintcache и package-lock.json не должны отслеживаться гитом

2021-09-29 16:41 UTC, OKitel commented on src/App.tsx
> +
Эти комментарии не нужны, потому что все роуты есть в Invitation

2021-09-29 16:45 UTC, OKitel commented on src/pages/Lobby/Lobby.tsx
> +import MembersField from '../../components/MembersField/MembersField';
Я переделала в своей ветке со стилями на нормальные импорты и избавилась от дефолтных экспортов.

2021-09-29 18:39 UTC, MarharytaKrasikava requested changes

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/CancelButton/CancelButton.tsx
> +export default CancelButton;
почему все еще экспорт дефолт?

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/CardAddForm/CardAddForm.tsx
> +                    {inputData.map(({ label, required, value, onChange, name }) => {
тут может быть больше одного элемента массива?

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/GameInfo/GameInfo.tsx
> +            {}
лишние скобки

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/GameInfo/GameInfo.tsx
> +    const hendler = (event: React.KeyboardEvent) => {
hAndler

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/GameSettings/GameSettings.tsx
> +export default GameSettings;
export const

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/GameSettings/Timer.tsx
> +                // label="minutes"
коммент

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/GameSettings/Timer.tsx
> +                    hendler(time.minutes * 50 + time.seconds);
вынести в отдельный хендлер и пробел выше убрать, плиз

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/IssueCreateForm/IssueCreateForm.tsx
> +    ];
что-то я не уверена, что так короче, и читается хуже, чем в jsx это прописывать

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/LinkToLobby/LinkToLobby.tsx
> +export default LinkToLobby;
экспорт

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/MembersField/MembersField.tsx
> +export default MembersField;
экспорт

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/Components/ScramMaster/ScramMaster.tsx
> +export default ScramMaster;
экспорт

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/components/GameCards/CardBack.tsx
> +    const hendler = () => {
hAndler

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/data.ts
> +import { ICard, IIssues, IMessage, IUserCard } from './types';
такие данные должны в папке shared храниться

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/pages/Game/Game.tsx
> +export default Game;
экспорт... а в чем назначение этого файла?

2021-09-29 18:39 UTC, MarharytaKrasikava commented on src/pages/Lobby/Lobby.tsx
> +                        {' '}
скобки

2021-09-29 18:41 UTC, OKitel commented on src/Components/CancelButton/CancelButton.tsx
> +export default CancelButton;
Я сделала ответвление от этой ветки, где правлю стили, и дефолтный экспорт тоже убрала.

2021-09-29 18:42 UTC, OKitel commented on src/Components/GameSettings/GameSettings.tsx
> +export default GameSettings;
Исправлено в ветве lobby-styles

2021-09-29 18:42 UTC, OKitel commented on src/Components/LinkToLobby/LinkToLobby.tsx
> +export default LinkToLobby;
Исправлено

2021-09-29 18:43 UTC, OKitel commented on src/Components/ScramMaster/ScramMaster.tsx
> +export default ScramMaster;
Исправлено

2021-09-29 18:43 UTC, OKitel commented on src/Components/MembersField/MembersField.tsx
> +export default MembersField;
Исправлено

2021-09-30 08:13 UTC, lexomut commented on src/data.ts
> +import { ICard, IIssues, IMessage, IUserCard } from './types';
старый файл демо, удалил

2021-09-30 08:14 UTC, lexomut commented on src/pages/Game/Game.tsx
> +export default Game;
старая заглушка , удалил

2021-09-30 08:16 UTC, lexomut commented on src/pages/Lobby/Lobby.tsx
> +                        {' '}
убрал, почему то преттер подставляет

2021-09-30 08:19 UTC, lexomut commented on src/components/GameCards/CardBack.tsx
> +    const hendler = () => {
исправил

2021-09-30 08:20 UTC, lexomut commented on src/Components/GameInfo/GameInfo.tsx
> +    const hendler = (event: React.KeyboardEvent) => {
исправил

2021-09-30 08:21 UTC, lexomut commented on src/Components/GameInfo/GameInfo.tsx
> +            {}
исправил

2021-09-30 08:28 UTC, lexomut commented on .gitignore
не убирал, эти строки ниже

2021-09-30 08:28 UTC, lexomut commented on src/App.tsx
> +
ок

2021-09-30 08:29 UTC, lexomut commented on src/pages/Lobby/Lobby.tsx
> +import MembersField from '../../components/MembersField/MembersField';
ок, это от Ленара ещё осталось

2021-09-30 08:47 UTC, lexomut commented on src/Components/GameSettings/Timer.tsx
> +                    hendler(time.minutes * 50 + time.seconds);
сделал

2021-09-30 09:00 UTC, lexomut commented on src/Components/IssueCreateForm/IssueCreateForm.tsx
> +    ];
переделал

2021-09-30 09:00 UTC, lexomut commented on src/Components/GameSettings/Timer.tsx
> +                // label="minutes"
исправил

2021-09-30 09:07 UTC, lexomut commented on src/Components/CardAddForm/CardAddForm.tsx
> +                    {inputData.map(({ label, required, value, onChange, name }) => {
переделал

2021-09-30 18:58 UTC, MarharytaKrasikava approved these changes

2021-10-01 09:54 UTC, merged