Vote
lexomut/Pointing-Poker pull request #26
Opened 2021-10-01 17:44 UTC by lexomut

реализовал удаление из игры игроков диллером или  большинством 
![Screenshot_2](https://user-images.githubusercontent.com/61846514/135664390-ad62e9f2-6633-4e1a-9608-55cb69cb47a0.png)

2021-10-01 22:12 UTC, OKitel requested changes
Я потестировала руками, но у меня никакого голосования не было. Только дилер удалил игрока и у него появилось сообщение, что его выкинули. Еще заметила, что после того, как игрока выкинуло из игры, он может вернуться к попапу для подключения к лобби и войти снова. Но его карточка уже не появляется. Нам надо добавить механизм подтверждения входа дилером. Я попап делала в игре, но можно и сюда его перетащить.

2021-10-01 22:12 UTC, OKitel commented on src/Components/VoteForm/VoteForm.tsx
> +    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
```suggestion
    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>): Promise<void> => {
```

2021-10-01 22:12 UTC, OKitel commented on src/Components/VoteForm/VoteForm.tsx
> +                    Dont kick
```suggestion
                    Don't kick
```

2021-10-01 22:12 UTC, OKitel commented on src/api/WSProvider.ts
> +            console.log('Ошибка отправки', e);
Нужно убрать лог

2021-10-01 22:12 UTC, OKitel commented on src/components/UserCard/UserCard.tsx
> +                return;
Тут как-то не вяжется, либо знак не тот, либо сообщение.

2021-10-01 22:12 UTC, OKitel commented on src/components/UserCard/UserCard.tsx
> +    const clickHandler = async () => {
```suggestion
    const clickHandler = async (): Promise<void> => {
```

2021-10-01 22:12 UTC, OKitel commented on src/components/invitation/Invitation.tsx
> +            {' '}
```suggestion
           
```

2021-10-01 22:12 UTC, OKitel commented on src/components/invitation/Invitation.tsx
> +                    <h4>YOU KICKED</h4>
```suggestion
                    <h4>YOU WERE KICKED</h4>
```

2021-10-01 22:12 UTC, OKitel commented on src/pages/Lobby/Lobby.tsx
> +    function checkVoted() {
```suggestion
    function checkVoted(): boolean {
```

2021-10-02 21:56 UTC, OKitel commented on src/components/invitation/Invitation.tsx
> +                    <h4>YOU KICKED</h4>
Может сюда еще добавить таймаут, чтобы по истечении 5 секунд переводило на мэйн?

2021-10-03 12:32 UTC, lexomut commented on src/Components/VoteForm/VoteForm.tsx
> +    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
по условиям голосование работает когда больше 3 игроков не считая    дилера.
и игрок входит в лобби  как новый пользователь

2021-10-03 12:35 UTC, lexomut commented on src/components/UserCard/UserCard.tsx
> +                return;
`> =`

2021-10-03 12:48 UTC, lexomut commented on src/components/UserCard/UserCard.tsx
> +                return;
если в лобби менее 3 человек, не считая дилера

2021-10-03 13:00 UTC, lexomut commented on src/api/WSProvider.ts
> +            console.log('Ошибка отправки', e);
давай пока оставим для отладки и уберем в финальной версии

2021-10-03 13:16 UTC, lexomut commented on src/components/invitation/Invitation.tsx
> +                    <h4>YOU KICKED</h4>
добавил

2021-10-03 13:25 UTC, OKitel commented on src/components/UserCard/UserCard.tsx
> +                return;
Так должно быть globalState.game.users.length < 4

2021-10-04 07:51 UTC, lexomut commented on src/components/UserCard/UserCard.tsx
> +                return;
да моя ошибка, исправил. спасибо

2021-10-04 13:20 UTC, OKitel commented on src/Components/VoteForm/VoteForm.tsx
> +                    Don &#39 t kick
```suggestion
                    Don &#39; t kick
```

2021-10-04 15:55 UTC, OKitel commented on src/Components/GameSettings/Timer.tsx
> +
А я в ветке game уже исправила эту ошибку, только по-другому

2021-10-04 16:34 UTC, lexomut commented on src/Components/GameSettings/Timer.tsx
> +
у тебя лучше

2021-10-04 16:45 UTC, OKitel commented on src/Components/GameSettings/Timer.tsx
> +
Тогда может откати эти изменения и оставь, как было. Когда мерж будем делать, будет проще

2021-10-04 16:49 UTC, OKitel commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.module.scss
> +    justify-content: space-between;
```suggestion
    justify-content: center;

```

2021-10-04 16:49 UTC, OKitel commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.module.scss
> +    justify-content: space-between;
Чтобы по центру заголовок был

2021-10-04 16:51 UTC, OKitel approved these changes

2021-10-04 19:15 UTC, MarharytaKrasikava requested changes

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.tsx
> +                    Kick him
him/her

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.tsx
> +                        globalState.ws.provider?.changeValueOfGameProperty('kickedUsersID', [
вынести хендлер бы

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.tsx
> +                        globalState.ws.provider?.changeValueOfGameProperty('pendingUsers', [
а эта часть дублируется, значит тоже отдельный колбек можно создать

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/Components/VoteForm/VoteForm.tsx
> +                    Don &#39 t kick
Можно просто No либо Not to kick

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/Components/VoteForm/VoteForm.tsx
> +             enters kick user ${
а какая тут полная фраза получается, что-то не могу понять. Вопрос что ли?

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/components/UserCard/UserCard.tsx
> +    const clickHandler = async (): Promise<void> => {
можно тут сделать дистрактуктуринг, а то очень уж длинные перечисления полей.
`const { currentUser, ws, game} = globalState;`. И ниже тоже много где такая же проблема

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/components/UserCard/UserCard.tsx
> +        } else {
else if () {}. Нужно избегать лишней вложенности блоков

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/components/game/Game.tsx
> +    }, [globalState]);
и этот эффект при любом изменении глобал стейта будет вызываться? Может, только отдельные поля в зависимости указать?

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/components/invitation/Invitation.tsx
> +                <Route exact path={`${path}`}>
path={path}

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/pages/Lobby/Lobby.tsx
> +            if (globalState.game.status !== 'new') {
это условие можно вынести к первому if:
`if (globalState.game.kickedUsersID.some((item: string) => item === globalState.currentUser.userID,) || globalState.game.status == 'new') { return; }`

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/pages/Lobby/Lobby.tsx
> +        function passNext() {
зачем тут функцию создавать, если она тут же вызывается?

2021-10-04 19:15 UTC, MarharytaKrasikava commented on src/pages/Lobby/Lobby.tsx
> +            return false;
это все в одно условие надо объединить через `||`

2021-10-04 20:25 UTC, lexomut commented on src/components/game/Game.tsx
> +    }, [globalState]);
в объекте provider поле с  globalState в объекте provider само не обновляется, и чтоб  всегда там  это поле было актуальное, пришлось сделать, метод который надо постоянно вызывать и передавать в него актуальный globalState .

2021-10-05 07:52 UTC, lexomut commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.tsx
> +                    Kick him
исправил

2021-10-05 07:56 UTC, lexomut commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.tsx
> +                        globalState.ws.provider?.changeValueOfGameProperty('kickedUsersID', [
исправил

2021-10-05 07:58 UTC, lexomut commented on src/Components/LetInUserToGameForm/LetInUserToGameForm.tsx
> +                        globalState.ws.provider?.changeValueOfGameProperty('pendingUsers', [
исправил

2021-10-05 08:09 UTC, lexomut commented on src/Components/VoteForm/VoteForm.tsx
> +             enters kick user ${
исправил

2021-10-05 08:18 UTC, lexomut commented on src/components/UserCard/UserCard.tsx
> +    const clickHandler = async (): Promise<void> => {
исправил кроме currentUser, это переменная из пропсов приходит

2021-10-05 08:20 UTC, lexomut commented on src/components/UserCard/UserCard.tsx
> +        } else {
исправил

2021-10-05 08:26 UTC, lexomut commented on src/components/invitation/Invitation.tsx
> +                <Route exact path={`${path}`}>
исправил

2021-10-05 08:33 UTC, lexomut commented on src/pages/Lobby/Lobby.tsx
> +            if (globalState.game.status !== 'new') {
исправил

2021-10-05 08:36 UTC, lexomut commented on src/pages/Lobby/Lobby.tsx
> +        function passNext() {
убрал

2021-10-05 08:39 UTC, lexomut commented on src/pages/Lobby/Lobby.tsx
> +            return false;
переделал

2021-10-05 18:38 UTC, MarharytaKrasikava approved these changes

2021-10-05 18:42 UTC, merged