reusable button component , create issue button
lexomut/Pointing-Poker pull request #3
Opened 2021-09-07 21:28 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/132413209-0680b093-722e-452e-8785-f997ab9537bd.png)

2021-09-08 07:48 UTC, lexomut approved these changes

2021-09-10 11:29 UTC, MarharytaKrasikava requested changes

2021-09-10 11:29 UTC, MarharytaKrasikava commented on src/App.tsx
> +            <IssueButton onClick={() => alert('Put logic here')} />
Это временная мера? Здесь должен быть раутинг реализован, правильно?

2021-09-10 11:29 UTC, MarharytaKrasikava commented on src/components/buttons/IssueButton.tsx
> +    const { onClick } = props;
Скорее всего эта кнопка будет содержать свой специфический хендлер, поэтому пропсами его не за чем передвать, не так ли?

2021-09-10 11:29 UTC, MarharytaKrasikava commented on src/components/buttons/Button.tsx
> +        <MaterialButton color="primary" variant={variant} onClick={onClick}>
я вот даже не знаю, стоит ли на данном этапе эту кнопку выносить, если в material-ui уже есть готовый "вынесенный" компонент. Когда будет необходимо снабдить логикой эти кнопки, возможно, каждую отдельную кнопку нужно будет вынести как отдельный компонент.

2021-09-10 19:57 UTC, OKitel commented on src/App.tsx
> +            <IssueButton onClick={() => alert('Put logic here')} />
Да, это просто демо

2021-09-10 20:08 UTC, OKitel commented on src/components/buttons/IssueButton.tsx
> +    const { onClick } = props;
Сделала хэндлер в самой кнопке

2021-09-10 20:09 UTC, OKitel commented on src/components/buttons/Button.tsx
> +        <MaterialButton color="primary" variant={variant} onClick={onClick}>
удалила

2021-09-12 15:24 UTC, MarharytaKrasikava approved these changes

2021-09-12 15:24 UTC, MarharytaKrasikava commented on src/components/buttons/IssueButton.tsx
> +    const handlerClick = useCallback(() => {
useCallback тут не нужен, поскольку не содержит зависимостей, обновляющих его.

2021-09-13 15:40 UTC, OKitel commented on src/components/buttons/IssueButton.tsx
> +    const handlerClick = useCallback(() => {
Done

2021-09-13 18:12 UTC, MarharytaKrasikava approved these changes

2021-09-13 23:41 UTC, merged