switch component
lexomut/Pointing-Poker pull request #4
Opened 2021-09-07 21:59 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/132416184-fce90d88-2d92-49c6-8863-b9efc0579f20.png)

2021-09-08 07:26 UTC, lexomut approved these changes

2021-09-08 07:28 UTC, lexomut reviewed
все ок

2021-09-10 11:32 UTC, MarharytaKrasikava requested changes

2021-09-10 11:32 UTC, MarharytaKrasikava commented on src/App.tsx
> +    const [switchOne, setSwitchOne] = useState(true);
этот стейт связан исключительно с компонетом Switch, поэтому он не должен здесь находиться

2021-09-10 20:19 UTC, OKitel commented on src/App.tsx
> +    const [switchOne, setSwitchOne] = useState(true);
Поместила стейт в сам компонент свитч

2021-09-12 15:26 UTC, MarharytaKrasikava approved these changes

2021-09-12 15:26 UTC, MarharytaKrasikava commented on src/components/switch/Switch.tsx
> +};
тут нужна пустая строка между типом и компонентом

2021-09-13 15:41 UTC, OKitel commented on src/components/switch/Switch.tsx
> +};
Done

2021-09-13 23:46 UTC, merged