create user function and read avatar function
lexomut/Pointing-Poker pull request #5
Opened 2021-09-08 14:15 UTC by lexomut

2021-09-10 20:21 UTC, OKitel approved these changes

2021-09-12 15:27 UTC, MarharytaKrasikava requested changes

2021-09-12 15:27 UTC, MarharytaKrasikava commented on src/api/ReadAvatar.ts
> +export default readAvatar;
избавляемся от экспорт дефолт

2021-09-13 15:52 UTC, lexomut commented on src/api/ReadAvatar.ts
> +export default readAvatar;
исправлено

2021-09-13 18:14 UTC, MarharytaKrasikava approved these changes

2021-09-16 13:52 UTC, merged