Issue card
lexomut/Pointing-Poker pull request #6
Opened 2021-09-08 19:03 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/132569468-63e3f413-645a-4818-bd08-ed2e9bad6288.png)

2021-09-10 11:43 UTC, MarharytaKrasikava requested changes

2021-09-10 11:43 UTC, MarharytaKrasikava commented on src/App.tsx
> +                }}
надо убрать в компонент, не за чем пропсом передавать этот хендлер

2021-09-10 20:25 UTC, OKitel commented on src/App.tsx
> +                }}
Done

2021-09-11 08:56 UTC, lexomut approved these changes

2021-09-12 15:29 UTC, MarharytaKrasikava approved these changes

2021-09-12 15:43 UTC, MarharytaKrasikava requested changes

2021-09-12 15:43 UTC, MarharytaKrasikava commented on src/components/IssueCard/IssueCard.tsx
> +    const handlerClick = useCallback(() => {
Не нужен useCallback

2021-09-13 15:46 UTC, OKitel commented on src/components/IssueCard/IssueCard.tsx
> +    const handlerClick = useCallback(() => {
Done

2021-09-13 18:15 UTC, MarharytaKrasikava approved these changes

2021-09-13 23:47 UTC, merged