user card
lexomut/Pointing-Poker pull request #7
Opened 2021-09-09 20:32 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/132758387-1d631dc5-4c21-4a51-8616-0b60b479413d.png)

2021-09-10 13:04 UTC, MarharytaKrasikava requested changes

2021-09-10 13:04 UTC, MarharytaKrasikava commented on src/components/UserCard/UserCard.tsx
> +        paddingLeft: 5,
лучше использовать "padding: 0 0 0 5px"

2021-09-10 13:04 UTC, MarharytaKrasikava commented on src/components/UserCard/UserCard.tsx
> +                {!imgSrc && <Avatar className={classes.avatar}>{initials}</Avatar>}
это нужно тернарным оператором заменить

2021-09-10 13:04 UTC, MarharytaKrasikava commented on src/App.tsx
> +            <UserCard
все, что здесь юзеров касается, в отдельный компонент нужно вынести

2021-09-10 20:26 UTC, OKitel commented on src/components/UserCard/UserCard.tsx
> +        paddingLeft: 5,
done

2021-09-10 20:28 UTC, OKitel commented on src/components/UserCard/UserCard.tsx
> +                {!imgSrc && <Avatar className={classes.avatar}>{initials}</Avatar>}
done

2021-09-10 20:30 UTC, OKitel commented on src/App.tsx
> +            <UserCard
Это только демо. Я могу сразу удалить эти примеры user card из app. Либо пока оставить, чтобы ребята видели, как использовать.
Как лучше поступить?

2021-09-11 08:41 UTC, lexomut approved these changes

2021-09-12 15:41 UTC, MarharytaKrasikava requested changes

2021-09-12 15:41 UTC, MarharytaKrasikava commented on src/App.tsx
> +            <UserCard
не нужно удалять. Вынесение списка юзер-карт в отдельный компонент не повлияет на отображение

2021-09-13 15:55 UTC, OKitel commented on src/App.tsx
> +            <UserCard
Вынесла в отдельный компонент

2021-09-13 18:21 UTC, MarharytaKrasikava requested changes

2021-09-13 18:21 UTC, MarharytaKrasikava commented on src/App.tsx
> +            <UserCard
не вижу коммита с изменениями по вынесению компонента

2021-09-13 18:21 UTC, MarharytaKrasikava commented on src/App.tsx
> +                }}
в этом хендлере в будущем должен быть запрос на сервер с ID участника (или именем), так что хендлер тут будет один - в самом компоненте User, а принимать как аргумент он будет разные ID. И передавать его не нужно

2021-09-13 18:21 UTC, MarharytaKrasikava commented on src/components/UserCard/UserCard.tsx
> +        position: 'absolute',
а без абсолюта тут никак?

2021-09-13 22:09 UTC, OKitel commented on src/App.tsx
> +                }}
Переделала

2021-09-13 22:09 UTC, OKitel commented on src/components/UserCard/UserCard.tsx
> +        position: 'absolute',
Переделала с помощью grid

2021-09-13 22:10 UTC, OKitel commented on src/App.tsx
> +            <UserCard
Запушила

2021-09-14 13:40 UTC, MarharytaKrasikava approved these changes

2021-09-14 17:54 UTC, merged