Header
lexomut/Pointing-Poker pull request #8
Opened 2021-09-09 21:46 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/132766873-9eb3a585-0591-46c9-a7f9-83a888f27511.png)

2021-09-10 13:13 UTC, MarharytaKrasikava requested changes

2021-09-10 13:13 UTC, MarharytaKrasikava commented on src/components/header/Header.tsx
> +        position: 'absolute',
вообще абсолютом нужно пользоваться только при крайней необходимости. Может, гдесь возможно через position: relative сдвинуть изображение и фаб вертикально вниз?

2021-09-10 13:13 UTC, MarharytaKrasikava commented on src/components/header/Header.tsx
> +        position: 'absolute',
тут что-то одно наверно надо сделать relative, а второй элемент относительно этого будет точно внутри него? или я не правильно понимаю назначние этого fab...

2021-09-10 20:44 UTC, OKitel commented on src/components/header/Header.tsx
> +        position: 'absolute',
Все верно понимаете, переделала

2021-09-10 20:46 UTC, OKitel commented on src/components/header/Header.tsx
> +        position: 'absolute',
переделала

2021-09-11 08:38 UTC, lexomut approved these changes

2021-09-12 15:45 UTC, MarharytaKrasikava approved these changes

2021-09-13 23:35 UTC, merged