footer without absolute
lexomut/Pointing-Poker pull request #9
Opened 2021-09-10 21:03 UTC by OKitel

![image](https://user-images.githubusercontent.com/79774026/132917408-b3e3d0f6-51b9-4c85-8fcb-6eeb5041a827.png)

2021-09-12 15:52 UTC, MarharytaKrasikava commented on src/App.tsx
>          <div className={styles.container}>
Обязательно ли оборачивание всего контента, хедера и футера в `<div><div/>`? Правильная страница должна состоять из семантических блоков - `<body><header/><main/><footer/></body>`

2021-09-13 23:34 UTC, OKitel commented on src/App.tsx
>          <div className={styles.container}>
Я так понимаю, что это вопрос того, куда и как мы рендерим. Сейчас футер лежит в апп, который рендерится в рут, который сам по себе уже див. Значит надо выносить футер и хедер на уровень индекс.тс, чтобы положить их снаружи апп, и это все рендерить просто в боди. Так? 
Если  я просто заменю див на diamond, то я уже не смогу применять на него классы. В общем, я не совсем понимаю, что с этим делать.

2021-09-14 14:40 UTC, MarharytaKrasikava commented on src/App.tsx
>          <div className={styles.container}>
ну да, с `<body>` я погорячилась :) Но тогда в App.tsx должно быть так:
`<>
    <Header/>
    <Main />
    <Footer />
</>`

2021-09-14 14:44 UTC, MarharytaKrasikava requested changes

2021-09-14 14:44 UTC, MarharytaKrasikava commented on src/App.tsx
>          <div className={styles.container}>
стили можно применить в `<div id="root">`

2021-09-14 14:44 UTC, MarharytaKrasikava commented on src/App.tsx
>          <div className={styles.container}>
а вместо `<Main>` должен быть раутинг настроен в будущем

2021-09-14 18:29 UTC, OKitel commented on src/App.tsx
>          <div className={styles.container}>
Переделала

2021-09-15 12:23 UTC, MarharytaKrasikava requested changes

2021-09-15 12:23 UTC, MarharytaKrasikava commented on src/App.tsx
> +            <div className={styles.fakeHeader}>Header will be here</div>
используйте тут сразу тег `<header>`, пожалуйста

2021-09-15 12:23 UTC, MarharytaKrasikava commented on src/index.scss
> +  min-height: 100vh;
а в чем смысл min-height? почему не height?

2021-09-15 13:26 UTC, OKitel commented on src/App.tsx
> +            <div className={styles.fakeHeader}>Header will be here</div>
Done

2021-09-15 13:26 UTC, OKitel commented on src/index.scss
> +  min-height: 100vh;
change to height

2021-09-15 17:28 UTC, MarharytaKrasikava approved these changes

2021-09-15 21:21 UTC, merged